name: iotdevice-device-controller
base: core22
version: '22'
summary: Device Controller REST API for Demo Purposes
description: |
  This is the REST API that provides data to the main UI
  application.

grade: stable
confinement: strict

architectures:
  - build-on: arm64
  - build-on: amd64
  - build-on: riscv64

apps:
  device-controller:
    command: bin/uvicorn app.main:app

  device-controller-service:
    command: launch.sh
    daemon: simple
    plugs:
      - network
      - network-bind

parts:
  device-controller:
    plugin: python
    source: device-controller
    python-requirements:
      - requirements.txt

  python-source:
    source: device-controller
    plugin: dump

  launcher:
    source: bin
    plugin: dump
